[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "terminal âš™ï¸"
path = "~"
startup_command = "fastfetch"
preview_command = "fastfetch"

[[session]]
name = "home ğŸ "
path = "~"
startup_command = "fd --type f --hidden --exclude .git | fzf-tmux -p --reverse | xargs nvim"
preview_command = "eza --all --icons --color=always {}"

[[session]]
name = "downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "ls; yazi"

[[session]]
name = "music ğŸµ"
path = "~/Music"
startup_command = "ls"

[[session]]
name = "tmux config âš™ï¸"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"
